name:                uhf
version:             0.0.0

dependencies:
  - base >= 4.13 && < 5

  - tasty
  - tasty-hunit
  - tasty-th

ghc-options:
  - -Wall

library:
  source-dirs: src

  dependencies:
    - text
    - safe
    - Decimal
    - containers
    - template-haskell
    - ansi-terminal
    - mtl

executables:
  uhfi:
    main: Main.hs
    source-dirs: exe/uhfi

    dependencies:
      - uhf

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  uhfc:
    main: Main.hs
    source-dirs: exe/uhfc

    dependencies:
      - uhf

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  uhf-test:
    main: uhf.hs
    source-dirs: test/

    dependencies:
      - uhf
