name:                uhf
version:             0.0.0

dependencies:
  - base >= 4.13 && < 5

ghc-options:
  - -Wall
  - -Wextra
  - -Wno-name-shadowing
  - -Werror=incomplete-patterns
  - -Werror=incomplete-uni-patterns
  - -Werror=missing-fields

default-extensions:
  - LambdaCase
  - TupleSections
  - TemplateHaskell
  - OverloadedStrings
  - NoImplicitPrelude
# TODO: split tests from library, but somehow still allow access to test private functions and things

library:
  source-dirs: src

  dependencies:
    - containers
    - ansi-terminal
    - text
    - safe
    - transformers
    - template-haskell
    - inflist
    - file-embed
    - filepath

    - tasty
    - tasty-hunit
    - tasty-th

executables:
  uhfc:
    main: Main.hs
    source-dirs: exe/uhfc

    dependencies:
      - uhf

      - text
      - optparse-applicative
      - containers

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  uhf-test:
    main: uhf.hs
    source-dirs: test/

    dependencies:
      - uhf
