name:                uhf
version:             0.0.0

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall -O0
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  uhfi:
    main:                Main.hs
    source-dirs:         src/interpreter

  uhfc:
    main:                Main.hs
    source-dirs:         src/compiler

tests:
  uhf-test:
    main:                Spec.hs
    source-dirs:         test
