name:                uhf
version:             0.0.0

dependencies:
  - base >= 4.7 && < 5
  - containers
  - text
  - safe
  - Decimal

  - tasty
  - tasty-hunit
  - tasty-th

ghc-options:
  - -Wall

internal-libraries:
  argparser:
    source-dirs: src/argparser

  io:
    source-dirs: src/io

  token:
    source-dirs: src/token

  lexer:
    source-dirs: src/lexer

    dependencies:
      - io
      - token

  compiler:
    source-dirs: src/compiler

executables:
  uhfi:
    main: Main.hs
    source-dirs: src/uhfi

    dependencies:
      - argparser

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  uhfc:
    main: Main.hs
    source-dirs: src/uhfc

    dependencies:
      - argparser

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  argparser-test:
    main: argparser.hs
    source-dirs: test/

    dependencies:
      - argparser

  io-test:
    main: io.hs
    source-dirs: test/

    dependencies:
      - io

  lexer-test:
    main: lexer.hs
    source-dirs: test/

    dependencies:
      - lexer
