name:                uhf
version:             0.0.0

dependencies:
  - base >= 4.7 && < 5
  - containers
  - text

  - HUnit

ghc-options:
  - -Wall

internal-libraries:
  argparser:
    source-dirs: src/argparser

  io:
    source-dirs: src/io

  token:
    source-dirs: src/token

  lexer: 
    source-dirs: src/lexer

    dependencies:
      - io

  compiler:
    source-dirs: src/compiler

executables:
  uhfi:
    main: Main.hs
    source-dirs: src/uhfi

    dependencies:
      - argparser

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  uhfc:
    main: Main.hs
    source-dirs: src/uhfc

    dependencies:
      - argparser

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  argparser-test:
    main: Spec.hs
    source-dirs: test/argparser

    dependencies:
      - argparser

  io-test:
    main: Spec.hs
    source-dirs: test/io

    dependencies:
      - io
