name:                uhf
version:             0.0.0

dependencies:
  - base >= 4.7 && < 5

  - tasty
  - tasty-hunit
  - tasty-th

ghc-options:
  - -Wall

internal-libraries:
  argparser:
    source-dirs: src/argparser

    dependencies:
      - containers

  io:
    source-dirs: src/io

    dependencies:
      - text
      - safe

  token:
    source-dirs: src/token

    dependencies:
      - Decimal

  ast:
    source-dirs: src/ast

    dependencies:
      - token

      - Decimal

  diagnostic:
    source-dirs: src/diagnostic

    dependencies:
      - io

      - span-helper

      - template-haskell
      - ansi-terminal
      - text
      - safe

  lexer:
    source-dirs: src/lexer

    dependencies:
      - io
      - token
      - diagnostic

      - span-helper

      - text
      - Decimal
      - safe

  parser:
    source-dirs: src/parser

    dependencies:
      - ast
      - io
      - token
      - diagnostic

      - text
      - mtl

  compiler:
    source-dirs: src/compiler

    dependencies:
      - io
      - diagnostic
      - lexer
      - token

      - text

  span-helper:
    source-dirs: test/span-helper

    dependencies:
      - io

      - text

executables:
  uhfi:
    main: Main.hs
    source-dirs: exe/uhfi

    dependencies:
      - argparser

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  uhfc:
    main: Main.hs
    source-dirs: exe/uhfc

    dependencies:
      - argparser
      - compiler
      - diagnostic
      - io

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  argparser-test:
    main: argparser.hs
    source-dirs: test/tests/

    dependencies:
      - argparser

  io-test:
    main: io.hs
    source-dirs: test/tests/

    dependencies:
      - io

  lexer-test:
    main: lexer.hs
    source-dirs: test/tests/

    dependencies:
      - lexer

  diagnostic-test:
    main: diagnostic.hs
    source-dirs: test/tests/

    dependencies:
      - diagnostic
