name:                uhf
version:             0.0.0

dependencies:
  - base >= 4.13 && < 5

  - tasty
  - tasty-hunit
  - tasty-th

ghc-options:
  - -Wall
  - -Wextra

default-extensions:
  - LambdaCase
  - TemplateHaskell
  - OverloadedStrings
# TODO: no implicit prelude
# TODO: split tests from library, but somehow still allow access to test private functions and things

library:
  source-dirs: src

  dependencies:
    - text
    - safe
    - Decimal
    - containers
    - template-haskell
    - ansi-terminal
    - mtl

executables:
  uhfc:
    main: Main.hs
    source-dirs: exe/uhfc

    dependencies:
      - uhf
      - optparse-applicative

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  uhf-test:
    main: uhf.hs
    source-dirs: test/

    dependencies:
      - uhf
