name:                uhf
version:             0.0.0

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall

internal-libraries:
  testing-lib:
    source-dirs: src/testing-lib

  argparser:
    source-dirs: src/argparser
    dependencies:
      - testing-lib

executables:
  uhfi:
    main: Main.hs
    source-dirs: src/interpreter

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  uhfc:
    main: Main.hs
    source-dirs: src/compiler

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  argparser-test:
    main: Spec.hs
    source-dirs: test/argparser

    dependencies:
      - testing-lib
      - argparser
